run:
  timeout: 5m
  go: "1.21"
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: false  # deprecated, use shadow instead
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: FreeBSD-Command-manager
  depguard:
    rules:
      main:
        files:
          - "main.go"
        allow:
          - "FreeBSD-Command-manager/cmd"
          - "FreeBSD-Command-manager/internal"
          - "FreeBSD-Command-manager/internal/jail"
          - "FreeBSD-Command-manager/internal/network/bareos"
          - "FreeBSD-Command-manager/pkg/ifconfig"
          - "github.com/spf13/cobra"
          - "fmt"
          - "os"
          - "encoding/json"
          - "net"
          - "regexp"
          - "strconv"
          - "strings"
          - "math/bits"
          - "os/exec"
          - "errors"
          - "log"
  forbidigo:
    rules:
      - name: println
        pattern: ^println$
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar  # replaces exportloopref
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
 #   - goimports
    - mnd  # replaces gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused  # replaces deadcode, structcheck, varcheck
    - whitespace
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - dupl
        - funlen
        - gocyclo
        - lll
        - thelper
        - tparallel
    - path: cmd/
      linters:
        - gomnd
        - goconst
        - dupl
        - funlen
        - gocyclo
        - lll
    - path: examples/
      linters:
        - gomnd
        - goconst
        - dupl
        - funlen
        - gocyclo
        - lll
        - thelper
        - tparallel
  max-issues-per-linter: 0
  max-same-issues: 0 